# Generated by Django 2.0.6 on 2018-06-24 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='Title post.', max_length=50, verbose_name='Title')),
                ('message', models.TextField(help_text='Your new message.', max_length=1500, verbose_name='Message')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Publication date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ('-pk',),
            },
        ),
    ]
