# Generated by Django 2.0.6 on 2018-06-24 16:19

from django.db import migrations, models
import social_network.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180624_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=social_network.core.utils.make_upload_path, validators=[social_network.core.utils.validate_image], verbose_name='Image'),
        ),
    ]
