# Generated by Django 2.0.6 on 2018-06-25 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_unlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.RemoveField(
            model_name='post',
            name='unlike',
        ),
    ]
