# Generated by Django 2.0.6 on 2018-06-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20180625_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_disable',
            field=models.BooleanField(default=False, verbose_name='Is disable?'),
        ),
    ]
