# Generated by Django 2.0.6 on 2018-06-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20180626_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_disable',
            field=models.BooleanField(default=False, verbose_name='Is disable?'),
        ),
    ]
