# Generated by Django 2.0.6 on 2018-06-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20180626_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default='', max_length=150, verbose_name='Message'),
        ),
    ]
