# Generated by Django 2.0.6 on 2018-06-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20180626_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(default='', help_text='Your new message.', max_length=1000, verbose_name='Message'),
        ),
    ]
