# Generated by Django 2.0.6 on 2018-07-01 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_post_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rating',
        ),
    ]
