# Generated by Django 2.0.6 on 2018-07-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_remove_post_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.IntegerField(blank=True, default=0, verbose_name='Rating'),
        ),
    ]
