# Generated by Django 2.0.6 on 2018-06-26 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import social_network.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=social_network.core.models.make_upload_path, validators=[social_network.core.models.validate_image], verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Publication date')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ('-pk',),
            },
        ),
    ]
